## Creating a dataframe

In [1]:
import pandas as pd

In [12]:
data={
    "Name":['Sandeep','Padmini','Shannu'],
    "Age":['39','37','6'],
    "City":['GDK','HYT','HYD']
}

In [13]:
df=pd.DataFrame(data)
print(df)

      Name Age City
0  Sandeep  39  GDK
1  Padmini  37  HYT
2   Shannu   6  HYD

In [14]:
df

      Name Age City
0  Sandeep  39  GDK
1  Padmini  37  HYT
2   Shannu   6  HYD

In [18]:
# From list of dictionaries
records=[
    {'Name':'Sandeep','Age':39,'City':'GDK'},
    {'Name':'Padmini','Age':37,'City':'HYT'},
    {'Name':'Shannu','Age':6,'City':'HYD'}
]
df=pd.DataFrame(records)
df

      Name  Age City
0  Sandeep   39  GDK
1  Padmini   37  HYT
2   Shannu    6  HYD

In [23]:
import numpy as np
# From numpy arrays
arr1=np.array([[1,2],[3,4],[5,6]])
arr1
df=pd.DataFrame(arr1,columns=['A','B'])
df

   A  B
0  1  2
1  3  4
2  5  6

In [25]:
data={
    "Name":['Sandeep','Padmini','Shannu'],
    "Age":['39','37','6'],
    "City":['GDK','HYT','HYD']
}
df=pd.DataFrame(data)
df

      Name Age City
0  Sandeep  39  GDK
1  Padmini  37  HYT
2   Shannu   6  HYD

In [ ]:
# Accessing the values
print(df['Name']) # Series (a column)
print('============')
print(df[['Name','Age']]) # Dataframe with 2 columns

0    Sandeep
1    Padmini
2     Shannu
Name: Name, dtype: str
============
      Name Age
0  Sandeep  39
1  Padmini  37
2   Shannu   6