# Iteration in Pandas

In pandas, iteration refers to looping over rows or columns of a DataFrame or Series. While pandas is optimized for vectorized operations, sometimes we need to loop — for example, for conditional logic, debugging, or generating complex values.

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Delhi', 'Mumbai', 'Chennai']
})

In [4]:
df

      Name  Age     City
0    Alice   25    Delhi
1      Bob   30   Mumbai
2  Charlie   35  Chennai

In [7]:
for index,row in  df.iterrows():
    print(f"{index: } Name: {row.Name} Age is: {row.Age} City: {row.City}")

 0 Name: Alice Age is: 25 City: Delhi
 1 Name: Bob Age is: 30 City: Mumbai
 2 Name: Charlie Age is: 35 City: Chennai

In [9]:
for row in  df.itertuples():
    print(f"{index: } Name: {row.Name} Age is: {row.Age} City: {row.City}")

 2 Name: Alice Age is: 25 City: Delhi
 2 Name: Bob Age is: 30 City: Mumbai
 2 Name: Charlie Age is: 35 City: Chennai

In [12]:
# Iterating Over Columns

for col in df.columns:
    print(f"Column: {col}")
    print(df[col].values, end='\n\n')

Column: Name
<StringArray>
['Alice', 'Bob', 'Charlie']
Length: 3, dtype: str

Column: Age
[25 30 35]

Column: City
<StringArray>
['Delhi', 'Mumbai', 'Chennai']
Length: 3, dtype: str

In [13]:
df

      Name  Age     City
0    Alice   25    Delhi
1      Bob   30   Mumbai
2  Charlie   35  Chennai

# Conditional Example: Add Column with Custom Logic

Based on age column, i want to create a new column that will classify people as 'young' or 'senior'

In [16]:
categories = []

# Loops

for idx, row in df.iterrows():
    print(row)
    print(row['Age'])

    if row['Age'] < 40 :
        categories.append("young")
    else :
        categories.append("senior")

df['Category'] = categories

df.head()

Name                       Alice
Age                           25
City                       Delhi
If_young_and_from_delhi     True
Name: 0, dtype: object
25
Name                          Bob
Age                            30
City                       Mumbai
If_young_and_from_delhi     False
Name: 1, dtype: object
30
Name                       Charlie
Age                             35
City                       Chennai
If_young_and_from_delhi      False
Name: 2, dtype: object
35

      Name  Age     City  If_young_and_from_delhi Category
0    Alice   25    Delhi                     True    young
1      Bob   30   Mumbai                    False    young
2  Charlie   35  Chennai                    False    young

# Better Way: Vectorized / Apply

In [17]:
df['Category_vectorized_1'] = df['Age'].apply(lambda age : 'young' if age < 40 else 'senior')

df['Category_vectorized_1'].head()

0    young
1    young
2    young
Name: Category_vectorized_1, dtype: str

In [18]:
categorize_age_lambda = lambda age : 'young' if age < 40 else 'senior'

df['Category_vectorized_2'] = df['Age'].apply(categorize_age_lambda)

df['Category_vectorized_2'].head()

0    young
1    young
2    young
Name: Category_vectorized_2, dtype: str

In [19]:
def categorize_age_function(age):
    # if age < 40:
    #     return 'young'
    # else :
    #     return 'senior'
    return 'young' if age < 40 else 'senior'

df['Category_vectorized_3'] = df['Age'].apply(categorize_age_function)

df['Category_vectorized_3'].head()

0    young
1    young
2    young
Name: Category_vectorized_3, dtype: str

In [20]:
df.head()

,Name,Age,City,If_young_and_from_delhi,Category,Category_vectorized_1,Category_vectorized_2,Category_vectorized_3
0,Alice,25,Delhi,True,young,young,young,young
1,Bob,30,Mumbai,False,young,young,young,young
2,Charlie,35,Chennai,False,young,young,young,young

In [21]:
for i in df[['Age', 'City']].iterrows():
    print(i)

(0, Age        25
City    Delhi
Name: 0, dtype: object)
(1, Age         30
City    Mumbai
Name: 1, dtype: object)
(2, Age          35
City    Chennai
Name: 2, dtype: object)

In [22]:
def check_if_delhi_and_young(row):
    print(row)
    city = row['City']
    age = row['Age']
    if city == 'Delhi':
        if age < 40:
            return True
        else :
            return False
    else:
        return False
    # return 'young' if age < 40 else 'senior'

df['If_young_and_from_delhi'] = df.apply(check_if_delhi_and_young, axis=1)

Name                       Alice
Age                           25
City                       Delhi
If_young_and_from_delhi     True
Category                   young
Category_vectorized_1      young
Category_vectorized_2      young
Category_vectorized_3      young
Name: 0, dtype: object
Name                          Bob
Age                            30
City                       Mumbai
If_young_and_from_delhi     False
Category                    young
Category_vectorized_1       young
Category_vectorized_2       young
Category_vectorized_3       young
Name: 1, dtype: object
Name                       Charlie
Age                             35
City                       Chennai
If_young_and_from_delhi      False
Category                     young
Category_vectorized_1        young
Category_vectorized_2        young
Category_vectorized_3        young
Name: 2, dtype: object